services:
  - type: web
    name: nsw-pwa-train-assistant
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: TFNSW_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NEXT_PUBLIC_URL
        sync: false
    healthCheckPath: /
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /sw.js
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /manifest.json
        name: Cache-Control
        value: public, max-age=31536000, immutable 